### ISSUE TITLE
Buttons seem to disappear when starting or ending calls.

### ISSUE THREAD

**Issue by cheatfreak47** [programmer2514/BetterDiscord-CollapsibleUI#10]
It seems like the buttons for toggling the UI seem to often disappear when a call starts or ends, often.
If enough UI is hidden, a user could conceivably get stuck and need to restart discord if they don't know how to use keyboard navigation.

**Comment by programmer2514** [comment]
I'm actively investigating this, but I can't seem to reproduce it. Do you think you could press Ctrl+Shift+I the next time it happens and send me a screenshot of the red error message in the Console tab? Thanks!

**Comment by TheHunter1234** [comment]
I am too getting this error it causes this to happen
![image](https://user-images.githubusercontent.com/69104450/149045367-9ff9bb83-bd5d-4166-bd47-21a52d7addb7.png)
you can reproduce it by changing channels or servers
currently using discord stable with the latest updates

**Comment by cheatfreak47** [comment]
The problem @TheHunter1234 posted I can confirm as well, it seems to be manifesting in a strange way on my end. And toggling this UI element cause me to lose my own user section and settings button, oddly.
https://i.imgur.com/yTNbSdu.png

I also have a unique problem likely because I use a discord plugin that shows call elapsed time on that area.

(Although that wasn't what the issue report originally was about)

I'm having a hard time reproducing the initial problem this topic was for as well, so it's possible it was fixed at some point by accident, still, leaving this open for the time being until I can be sure it's actually gone.

**Comment by TheHunter1234** [comment]
I do have a plugin that shows call time too.

**Comment by programmer2514** [comment]
I am aware of both issues and am working on a fix. I should have this and a few other things fixed by the end of the week :)

**Comment by programmer2514** [comment]
Both issues have been fixed in the dev branch
