### ISSUE TITLE
Autocollapse causes elements to uncollapse when entering fullscreen in a video

### ISSUE THREAD

**Issue by Doomelf** [programmer2514/BetterDiscord-CollapsibleUI#115]

**Comment by programmer2514** [comment]
I can't seem to reproduce this on my end - does this still happen on v8.1.0?

**Comment by Doomelf** [comment]
Found the issue. Had autocollapse enabled.

**Comment by programmer2514** [comment]
This shouldn't be happening, even with autocollapse enabled
