### ISSUE TITLE
Plugin fails to initialize in servers or group chats

### ISSUE THREAD

**Issue by Andy76swe** [programmer2514/BetterDiscord-CollapsibleUI#116]
When you have any server in the serverlist selected the uncollapsing is not working. Only when you have the Message section selected is it uncollapsing. Discord version Stable 264109 (2fa3773) Host 1.0.9032 x86 (43225)

**Comment by programmer2514** [comment]
Guys, I know the plugin is broken - I am pushing 14 hour days in college right now and have not had time to fix it. I apologize for the inconvenience, I will get around to it as soon as I have time
