### ISSUE TITLE
Servers list preview

### ISSUE THREAD

**Issue by Artaherzadeh** [programmer2514/BetterDiscord-CollapsibleUI#120]
Hi
I don't know if it's a bug or if you made a change but I prefer the previous servers list design. This new design doesn't match the overall design of Discord. Is there a way to change it to the previous design on my side?
![Screenshot 2024-02-10 111125](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/64541682/7820b1aa-2a28-4582-b8ac-9c2e59e97f90)

**Comment by programmer2514** [comment]
This is a bug, sorry about that - I should have it fixed shortly :)
