### ISSUE TITLE
@version 8.1.0 : META was not found in 

### ISSUE THREAD

**Issue by Adelscott** [programmer2514/BetterDiscord-CollapsibleUI#121]
Error when launching Discord with this new version : 8.1.0

8.0.0 works fine

![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/10946454/f9e382ca-405c-434a-9246-80652df12ef0)

**Comment by programmer2514** [comment]
Uhhh...what? I'm not sure what's in your CollapsibleUI.plugin.js file but it isn't the plugin lol

Try redownloading it from [here](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/releases/download/v8.1.0/CollapsibleUI.plugin.js) and replacing the file you already have.
