### ISSUE TITLE
Turning off sliding on user pannel and message bar

### ISSUE THREAD

**Issue by RandoUSser** [programmer2514/BetterDiscord-CollapsibleUI#122]
I was wondering where in the code i could fiddle to turn out the sliding on the user profile (mute/unmute, deafen/undefen and setting) and the sliding in the message bar (gif, stickers and emojis) so you dont have to hover over the specific area to make everything visible.
Thanks and sorry if the account looks sus. I only made it to ask about this plugin specifically

Refs, using the oldcord/dtm-16 theme if you are confused 
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/160346207/7a087858-e295-4210-b2dd-49dd6c969430)
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/160346207/843477f6-6f76-42b2-861d-b3c733beeef1)

Thanks once again

**Comment by programmer2514** [comment]
Hey, no worries. There's actually no reason to fiddle with the code, there are plugin settings for both of those.

If you go into the area where you enable/disable the plugin and click the settings icon under it, it should be under the Main subcategory: "Disable User Settings Auto-collapse" and "Disable Message Bar Button Auto-collapse" respectively.

![BetterDiscord Plugins Page](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/43104632/384e74d1-1272-45bc-967b-89be586927d6)
![CollapsibleUI Settings Page](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/43104632/90990040-df25-48d3-ab5d-23112f2ae426)
![Specified Settings](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/43104632/556c1939-f58f-4e22-8b05-cb77804f20bf)

**Comment by RandoUSser** [comment]
> Hey, no worries. There's actually no reason to fiddle with the code, there are plugin settings for both of those.
> 
> If you go into the area where you enable/disable the plugin and click the settings icon under it, it should be under the Main subcategory: "Disable User Settings Auto-collapse" and "Disable Message Bar Button Auto-collapse" respectively.
> 
> ![BetterDiscord Plugins Page](https://private-user-images.githubusercontent.com/43104632/305663588-384e74d1-1272-45bc-967b-89be586927d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDg1MzAsIm5iZiI6MTcwODI0ODIzMCwicGF0aCI6Ii80MzEwNDYzMi8zMDU2NjM1ODgtMzg0ZTc0ZDEtMTI3Mi00NWJjLTk2N2ItODliZTU4NjkyN2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNzMwOTdiNDY2NzBhYmI2ZjAzMWUxOTJjZTk2YmJlMTU4ZTQ0NmMwMWFhYjE5NGFjYWY1YzM0NTM2NjcwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2QnOkIpIGGh9XfQWei3e3jcr3vLxdPDTVnqGTUP1Po) ![CollapsibleUI Settings Page](https://private-user-images.githubusercontent.com/43104632/305663593-90990040-df25-48d3-ab5d-23112f2ae426.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDg1MzAsIm5iZiI6MTcwODI0ODIzMCwicGF0aCI6Ii80MzEwNDYzMi8zMDU2NjM1OTMtOTA5OTAwNDAtZGYyNS00OGQzLWFiNWQtMjMxMTJmMmFlNDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMjNkMzNhOGM2ZTNlNGY2MzMzOGY2MGZmNzFlYjZlMmExZDVlYmE5MDNiYzkwOWY2YTZmOWRlMWIzN2ExMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRLXubyE6e4svqzho2Al5mUL5m3wycBg5I13YDd9Ef8) ![Specified Settings](https://private-user-images.githubusercontent.com/43104632/305663687-556c1939-f58f-4e22-8b05-cb77804f20bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDg1MzAsIm5iZiI6MTcwODI0ODIzMCwicGF0aCI6Ii80MzEwNDYzMi8zMDU2NjM2ODctNTU2YzE5MzktZjU4Zi00ZTIyLThiMDUtY2I3NzgwNGYyMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MjE2ODQ3YzE3YmJlMGZiZTllMzRlMzRkZTlkNTEwZGJlYmUzMDUwZWFjYjBmYWE2YTY0MTJkMTRiYzM1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ljxDWFChemFsyXWTSPiYH2ZnjXqHVmWo7tt4Z3LSAXg)

Thank you :)
