### ISSUE TITLE
Please reduce the distance needed before the resize channel option shows up

### ISSUE THREAD

**Issue by ghost** [programmer2514/BetterDiscord-CollapsibleUI#128]
For context: I prefer the channel list to be smaller than than Discord default (image for comparison)
![Comparison](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/163866437/74d227bf-d9a1-4b34-97c8-bdfaf2ef876c)

Here's where my problem comes in: I have to click on the leftmost (or topmost) side of my settings icon in order to access settings, otherwise the plugin thinks I'm trying to resize the channel list. 

Would it be possible to reduce the distance needed to resize channel so the plugin doesn't think that my attempts to open settings is me trying to resize the channel list? 

Video of my issue: https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/163866437/cf85022c-7824-451b-8097-b647b217dac2

Edit: Just change my channel list width to check, and this seems to happen regardless of channel list width.

**Comment by programmer2514** [comment]
I cannot reproduce this behavior on my system - what plugins/themes do you have installed, and does the issue persist if you disable them? Additionally, what system are you using Discord on? Windows, or something else?

**Comment by roniberry** [comment]
System: Windows 10

Plugins: BDFDB, Image Utilities (Devilbro), Insert Timestamps (Vendicated), Invisible Typing (Strencher), Remove Blocked Users (Devilbro), Remove Chat Buttons (Qb), Split Large Messages (Devilbro), Translator (Devilbro), and Zeres Plugin Library.

Themes: Radial Status (Gibbu#1211) and Settinsg Modal (Devilbro)

Issue still exists even after I disable all my plugins and themes

**Comment by programmer2514** [comment]
What version of Discord do you use (Stable, PTB, Canary)?

**Comment by roniberry** [comment]
I use Stable Discord
I'm not sure if this is what you meant by monitor resolution and DPI scaling: 
![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/163866437/c4f76ffd-379d-4c86-b2dc-9a3cd6d45716)

**Comment by programmer2514** [comment]
That is exactly what I meant, thank you. It does appear to me to be a DPI scaling issue of some sort, although I still cannot reproduce it even with your settings - does this issue persist if you set your scaling to 100%?

**Comment by roniberry** [comment]
The issue persists at 100% DPI scale.

**Comment by programmer2514** [comment]
That is very odd...

The resizability feature itself is implemented natively (using the CSS resize attribute plus some JS for settings preservation), so there is nothing I know of that I can do to help, especially without the ability to reproduce it.

You could try completely re-installing Discord and BetterDiscord but I am not sure what else to suggest.

I will leave this issue open until it is resolved, but to my knowledge, this does not normally happen with my plugin installed.
