### ISSUE TITLE
Plugin broke after latest update.

### ISSUE THREAD

**Issue by Doomelf** [programmer2514/BetterDiscord-CollapsibleUI#131]

**Comment by herocheese** [comment]
Plugin non-functional after update. Uninstalling and reinstalling does nothing, as well as turning it off and on again.

**Comment by xArkailzx** [comment]
+1

**Comment by kojiinari** [comment]
+1 
After discord update, plugin no longer collapses UI.

stable 303390 (06f5b50)
Host 1.0.9151 x64 (48891) 
Build Override: N/A Windows 11 64-bit (10.0.22621)
Better Discord Core v1.10.2

**Comment by DontBotherYT** [comment]
+1 
Discord did break the plugins and connected libraries upon updating. 

stable 303557 (3b02892)
Host 0.0.57 x64 
Build Override: N/A Linux 64-bit (6.5.0-41-generic)
Better Discord Core v1.10.2

**Comment by TaPo4eK228** [comment]
+1
just not working
stable 303557 (3b02892) 
Host 1.0.9151 x64 (48891) 
Build Override: N/A Windows 11 64-bit (10.0.22631)
BetterDiscord Core v1.10.2

**Comment by programmer2514** [comment]
Apologies for the lack of response - I've been on vacation. I should have a fix posted soon, thanks for the report! ❤️
