### ISSUE TITLE
Keep the channel list open when switching servers

### ISSUE THREAD

**Issue by thenorili** [programmer2514/BetterDiscord-CollapsibleUI#134]
When switching servers to check for unread messages in their channels, the channel tray closes. I need to wiggle the mouse for it to open the channel tray again so that I can see if there are unread messages in the server I have selected.

I would prefer if the channel list stayed open until I moved my mouse away from the server list so that I could check several channels in quick succession without excessive animation or mouse-wiggling, similar to the behavior on mobile discord where you can check various servers while the channel list stays maximized until you focus a channel.

If some users rarely change servers and would prefer the current behavior, perhaps there could be a configuration option to leave the channel tray open when selecting a server.

**Comment by programmer2514** [comment]
This is actually a bug in the plugin's logic - Thanks for the report, I should have a fix out shortly :)

**Comment by thenorili** [comment]
I just downloaded the update, great work on the fast turnaround!
