### ISSUE TITLE
Gray bar at bottom of vc screen when using any zoom level lower than %100

### ISSUE THREAD

**Issue by SidesplitYT** [programmer2514/BetterDiscord-CollapsibleUI#138]
When zooming out discord lately using Collapsible UI, I get a gray bar at the bottom of the call instead of an all black background.

**To Reproduce**
1. Go to vc
2. Click on "Ctrl -" to zoom out
3. See gray bar at bottom of call

**Screenshots**
![Screenshot (1)](https://github.com/user-attachments/assets/7df38800-2aa8-4aee-93dd-3b8cda888bad)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Discord Version: Stable
 - Enabled Theme(s): Settings Modal
 - (OPTIONAL) Enabled Plugins: BDFDB, BetterVolume, CallTimeCounter, CollapsibleUI, DoNotTrack, MessageLoggerV2, ReadAllNotificationsButton, ServerDetails, XenoLib, ZeresPluginLibrary

**Additional context**
Occurs on both vertical, and horizontal monitors.

**Comment by programmer2514** [comment]
Fixed in v8.4.7. Thanks for the detailed report!

**Comment by SidesplitYT** [comment]
Dude, THANK YOU! Glad I could be of help and really glad to be rid of that pesky bar lol. Huge thanks man, keep doing what you're doing man!
