### ISSUE TITLE
Plugin stops working in Direct Messages Tab

### ISSUE THREAD

**Issue by BaderThanBad** [programmer2514/BetterDiscord-CollapsibleUI#139]
The Plugin stopped working on the direct messages tab. It used to work but stopped for some reason. Now when I hover or even press the hotkeys it does not do anything. It works fine in the servers tabs. The options in the plugins->settings to show/disable something still works but otherwise nothing else works.

Is this a bug or something I missed? It used to work perfect but at one startup it stopped working and I do not remember changing anything.

**Comment by programmer2514** [comment]
Fixed in v8.4.8 - Thanks for the report!
