### ISSUE TITLE
Status menu is flipped when using with another plugin

### ISSUE THREAD

**Issue by Adelscott** [programmer2514/BetterDiscord-CollapsibleUI#145]
**Describe the bug**
Status menu is flipped when using with CompleteTimestamps v1.6.9 from DevilBro

**To Reproduce**
1. Disable all plugins
2. Enable CollapsibleUI v8.5.0 & CompleteTimestamps v1.6.9
3. Click on user bottom left to show status menu

**Expected behavior**
![image](https://github.com/user-attachments/assets/2fa153e6-9bf3-48bb-99e1-639054d23395)

**Screenshots**
![image](https://github.com/user-attachments/assets/c825f79a-ea2e-4263-b8cd-1aaa2c5e95d4)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Discord Version: Stable
 - Enabled Theme(s): Dracula Officialv1.0.0by Dracula /  same without
 - (OPTIONAL) Enabled Plugins: No other than the 2 mentioned here.

**Comment by programmer2514** [comment]
Thank you for the report - I will look into this.

**Comment by Adelscott** [comment]
Thank you !
