### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ashergz** [programmer2514/BetterDiscord-CollapsibleUI#15]
Getting "CollapsibleUI could not be started" error.

**Comment by programmer2514** [comment]
This doesn't give me enough information to find the source of the problem. Could you press Ctrl+Shift+I, find the red-highlighted error, and send me a screenshot of it? Thanks

**Comment by ashergz** [comment]
![image](https://user-images.githubusercontent.com/35883201/149326007-678d7881-56c3-49a8-99da-a3d50deecdf3.png)

Hope this helps

**Comment by programmer2514** [comment]
Well, that's not the error, but I know the issue now. You're using v1.1.0 of the plugin, which has been pretty broken for months, but broke completely with the latest Discord update. The BD dev's won't update my plugin on their site for some reason, but for the time being you can download v4.0.0 here: 
https://raw.githubusercontent.com/programmer2514/BetterDiscord-CollapsibleUI/main/CollapsibleUI.plugin.js
(Right-click, save as...)
That should fix the problem and automatically keep your plugin updated from this point forward :)

**Comment by ashergz** [comment]
That did it. Thanks a lot!

**Comment by programmer2514** [comment]
No problem :)
