### ISSUE TITLE
Channel List resize not working

### ISSUE THREAD

**Issue by gohamstergo** [programmer2514/BetterDiscord-CollapsibleUI#151]
**Describe the bug**
Channels list drag-to-resize not working.

**To Reproduce**
Main > Resizable Channel List > Enable

**Expected behavior**
Attempting to drag from bottom right corner of list. Cursor changes, but dragging does nothing. Worked before BetterDiscord 1.11

**Desktop (please complete the following information):**
 - OS: Win10
 - Discord Version: Stable
 - Enabled Theme(s): None

**Comment by programmer2514** [comment]
This is caused by the same issue as #150, so I'm going to mark it as a duplicate - thanks for the report!

**Comment by gohamstergo** [comment]
appreciate your efforts!
