### ISSUE TITLE
CollapsibleUI is outdated?

### ISSUE THREAD

**Issue by Scorpions95** [programmer2514/BetterDiscord-CollapsibleUI#153]
CollapsibleUI says that it's outdated
but im useing latest version 9.0

**Comment by Scorpions95** [comment]
![outdated](https://github.com/user-attachments/assets/b151c3d5-1ed8-42b7-a4e6-b247fa768814)

**Comment by programmer2514** [comment]
v9.0.0 is not the latest release - v9.0.2 is. It fixes a few major issues present in v9.0.0 and can be downloaded here: https://github.com/programmer2514/BetterDiscord-CollapsibleUI/releases/latest
