### ISSUE TITLE
Plugin currently not working with latest stable Discord update!

### ISSUE THREAD

**Issue by Synonyx** [programmer2514/BetterDiscord-CollapsibleUI#16]
Enabling the plugin currently just leads to a  _"CollapsibleUI could not be started."_  error bubble appearing at the bottom of the window.

Discord Version: 
> Stable 110451 (c233a73)
> Host 1.0.9003, Windows 10 64-Bit (10.0.19042)

(If I can provide any more information let me know! I'm not the most knowledgeable with GitHub stuff.)

**Comment by programmer2514** [comment]
Duplicate of #15, #4, and #2
