### ISSUE TITLE
Collapse a panel when exiting the window

### ISSUE THREAD

**Issue by Albeoris** [programmer2514/BetterDiscord-CollapsibleUI#17]
I am using multiple monitors.

Discord is located on the left monitor. To move the mouse to an adjacent monitor, I need to swipe it over the collapsed contact area (on the right).

When you hover the mouse, it expands, but does not collapse when the mouse moves outside the window to the adjacent screen.

Because of this, the list of contacts remains expanded, and the text area narrows.

**Comment by programmer2514** [comment]
Thanks for the report, fixed in the latest release :)
