### ISSUE TITLE
collapsed ui won't un collapse

### ISSUE THREAD

**Issue by xenzer** [programmer2514/BetterDiscord-CollapsibleUI#18]
when i put my mouse where the ui collapses, it will not come back, I don't have ui transitions off and i have tried to mess with the un collapse distance, still nothing. the only thing i can think of is another plugin is breaking it, but it was working like 2 days ago so i have no clue

https://user-images.githubusercontent.com/74574555/150825231-aa1eaeca-56c3-455d-bf81-f01a76c16c90.mp4

**Comment by programmer2514** [comment]
Looks like Discord's latest update broke it again :/
Gimme a day or two and I'll have it up and running again. Thanks for the report!

**Comment by programmer2514** [comment]
Fixed in v4.0.4
