### ISSUE TITLE
DiscordNight: Don't autoshow members list if hovering over upload button

### ISSUE THREAD

**Issue by nearcatch** [programmer2514/BetterDiscord-CollapsibleUI#19]
The theme DiscordNight puts the upload button in the lower right of the message bar. Trying to press it makes the member list unhide and then shifts it away

https://user-images.githubusercontent.com/692914/151229558-74d3fe26-0ad0-4d98-a1a6-3614594c17d3.mp4

**Comment by programmer2514** [comment]
This is intended. However, it is configurable as well.
In the plugin settings (gear icon under CollapsibleUI in your Plugins list), you have 2 options:
1) Under the `Main` category, disable `Dynamic Uncollapse`
2) Also under the `Main` category, play around with the value of `Dynamic Uncollapse Distance (px)` until it works to your liking

**Comment by nearcatch** [comment]
> This is intended. However, it is configurable as well. In the plugin settings (gear icon under CollapsibleUI in your Plugins list), you have 2 options:
> 
>     1. Under the `Main` category, disable `Dynamic Uncollapse`
> 
>     2. Also under the `Main` category, play around with the value of `Dynamic Uncollapse Distance (px)` until it works to your liking

I'm aware it can be turned off. I like the dymanic uncollapse. I'm just requesting that the members list not uncollapse because the cursor is in the message area.

**Comment by programmer2514** [comment]
Ah yeah, I see what you're saying. The logic for that is a bit more complex, but I should be able to figure something out

**Comment by programmer2514** [comment]
Fixed in v4.0.6 (actually easier than I thought👍)

**Comment by nearcatch** [comment]
Doesn't seem to work for me.

https://user-images.githubusercontent.com/692914/151495582-ee6fd33c-6aea-4c83-9cf6-87b66a464a3f.mp4
```
Stable 112296 (15f81ca)
BetterDiscord 1.4.0
Host 1.0.9003 Windows 10 64-Bit (10.0.19044)
DiscordNight v0.9.5.1

**Comment by programmer2514** [comment]
Huh, looks like that button might not actually be part of the message bar container.. I'll probably have to add some compat code for that particular theme.

**Comment by nearcatch** [comment]
Works great now, thanks.
