### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by Masono03** [programmer2514/BetterDiscord-CollapsibleUI#2]
I just got this plugin and it fails to start no matter what. i dont know why tho. Does this conflict with any other plugin or is it something to do with the threads update? 

My plugin list is:
- AutoPlayGifs
- BDFDB
- BetterFormattingRedux
- BetterRoleColors
- CallTimeCounter
- CharCounter
- CollapsibleUI (This one but it just wont load)
- CompleteTimestamps
- CrashRecovery
- Double Click To Edit
- EmojiUtilities
- GameActivityToggle
- GifSaver
- GuildProfile
- ImageToClipboard
- ImageUtilities
- InvisibleTyping
- Link-Profile-Picture
- LinkBanner
- NoSpotifyPause
- NotificationSounds
- OldUpload
- OpenSpotify Links in Spotify
- PluginRepo
- ReadAllNotificationsButton
- Send BD Emotes
- ShowConnections
- ShowHiddenChannels
- SpellCheck
- SplitLargeMessages
- SpotifyControls
- StaffTag
- StatusEverywhere
- streamerModeOnGoLive
- ThemeRepo
- ThemeSettings
- TypingIndicator
- UserVoiceShow
- UserVolumeBooster
- XenoLib
- ZeresPluginLibrary

sorry for the long list but maybe one of them is conflicting and known to conflict and it would be great to know so yah...

**Comment by programmer2514** [comment]
I don't think any of those plugins should conflict. Try downloading the latest version (v2.0.1) directly from Github and see if that one works. Also, what theme are you using?

**Comment by Masono03** [comment]
AH yes wonderful the GitHUb one works :D i just garbbed it inside discord via plugin repo before and that one seems out of date/not working :) also theme i use: BlurpleRecolor

**Comment by programmer2514** [comment]
Great!

Yeah, the one in BD's repo is v1.1.0, which had some pretty glaring issues. I'm not really sure how to get the new version uploaded there atm, but I'll try to figure it out :) 

Also, I asked about the theme because CollapsibleUI's animations mess with the styling of some elements, which _could_ break certain themes. I'm hoping to add a settings option in the near future to toggle the animations so that it won't be an issue anymore.

Anyways, I'm glad the new version works for you! :)

**Comment by BlueStarBRS** [comment]
@programmer2514  your polugin in plugin repo and BDiscord is outdated on version v1.1.0

**Comment by programmer2514** [comment]
@BlueStarBRS I know, but unfortunately,  there's nothing I can do about it. The update has already been submitted, but it needs to be approved by a site admin before it can be pushed to the BD repo. In the meantime, if you download the latest version from Github, it will automatically update to the latest version from now on.
