### ISSUE TITLE
Window title bar "stuttering" on uncollapse

### ISSUE THREAD

**Issue by bajader** [programmer2514/BetterDiscord-CollapsibleUI#20]
![ezgif-2-b47bdfa07b](https://user-images.githubusercontent.com/98495831/151260884-c60b6e89-e4da-4da5-a55e-4e2f43ce51b2.gif)

**Comment by programmer2514** [comment]
That's strange. What do you have your dynamic uncollapse distance set to in the plugin settings?

**Comment by bajader** [comment]
Now i think its 35px but 20px also gave me this stuttering thing. Other collapsible panels are working correctly though. Also that bug started appearing a little before the whole auto uncollapse feature broke when discord changed some things. After update of your plugin it started working for a while and now it's the same bug again.

**Comment by programmer2514** [comment]
Huh, yeah, I am able to reproduce it on my installation. I'll look into it :)

**Comment by programmer2514** [comment]
Turns out this is an issue that goes all the way up to the web wrapper Discord uses (Electron): https://github.com/electron/electron/issues/8730
I'm trying to find a workaround but it's going to be a lot more complicated than I originally thought

**Comment by programmer2514** [comment]
Fixed (as well as it can be) in v4.0.5
