### ISSUE TITLE
Feature request: collapsible toolbar

### ISSUE THREAD

**Issue by wroyca** [programmer2514/BetterDiscord-CollapsibleUI#22]
The extension collapses the toolbar icons of CollapsibleUI without offering the possibility to collapse the whole toolbar at once. This makes the user interface look clumsy, as it is superimposed on the username when the minimum size requirement of discord is disabled. 

![Screenshot from 2022-04-05 17-57-35](https://user-images.githubusercontent.com/91024200/161857114-ca902312-d3d0-4dfe-93d8-641011491409.png)

**Comment by programmer2514** [comment]
This would be difficult at best to achieve. I may come back to it at some time in the future.

**Comment by programmer2514** [comment]
Added in v5
