### ISSUE TITLE
Request for compatibility with OldTitleBar

### ISSUE THREAD

**Issue by akumenon** [programmer2514/BetterDiscord-CollapsibleUI#29]
First off, thank you for making this. I'm really enjoying my time with this plugin.

As of now, when using [OldTitleBar](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/OldTitleBar/) and while on the friends/DMs tab, CollapsibleUI's buttons show up on the right of the close button. 
![image](https://user-images.githubusercontent.com/6745915/168527182-045b9413-c8fb-4114-902e-f33d0cc54ea6.png)
I hope it's not too much trouble to ask if you could make it so they appear on the left instead.

Thank you and best regards.

**Comment by programmer2514** [comment]
Fixed in upcoming release
