### ISSUE TITLE
Sections not collapsing when relevant button is not visible (set to 0).

### ISSUE THREAD

**Issue by akumenon** [programmer2514/BetterDiscord-CollapsibleUI#30]
Hello again 😀

Seems that disabling a button also disables collapsing if you've set it earlier. I'm not sure if this is a bug or a safety feature of sorts. Would you consider making it so that I can have sections collapse even if the relevant button were invisible? e.g. I've enabled collapsing for the server list and don't intend on changing it so I'd like to hide the button, but doing so would prevent it from collapsing even if `"cui.serverListButtonActive": "false"` (it actually works until you restart Discord).

I hope you'll look into it!

Thanks again.

**Comment by programmer2514** [comment]
This should be pretty easy to fix actually :)

**Comment by programmer2514** [comment]
Reopening this as a planned setting for an upcoming release
