### ISSUE TITLE
CollapsibleUI's buttons show up on the right (while in a guild, not in DMs) with KeywordTracker

### ISSUE THREAD

**Issue by akumenon** [programmer2514/BetterDiscord-CollapsibleUI#31]
Following up on #29, in v5.1.2, the plugin's buttons now show up correctly while in DMs, but are on the right of the close button while in a server/guild.

Sorry to bother you again with this 😅 and thank you for your hard work!

**Comment by programmer2514** [comment]
Huh, I can't seem to reproduce this. Do you happen to have a plugin/theme that removes the search bar?

**Comment by akumenon** [comment]
Oof I'm so sorry. You're right, it was a plugin ([KeywordTracker](https://github.com/sarahkittyy/KeywordTracker)) that adds a button in the same area.
I'll ask them if they could support OldTitleBar.

While finding the source of the problem, I did come across another bug though. 😬 I'll post about it after looking into it a bit more.

**Comment by programmer2514** [comment]
Haha okay, thanks for the reports :)

**Comment by programmer2514** [comment]
This appears to be happening again - reopening until I find a solution

**Comment by programmer2514** [comment]
This appears to have fixed itself? Weird...
