### ISSUE TITLE
Collapsible UI Gui not showing.

### ISSUE THREAD

**Issue by KingAlexey212** [programmer2514/BetterDiscord-CollapsibleUI#33]
After some update Collapsible UI just stopped working + settings failing to open.
![SimplyError](https://user-images.githubusercontent.com/63243069/170856756-8aa99384-7e95-4aca-b941-236349dc6fff.png)
![SettingsError](https://user-images.githubusercontent.com/63243069/170856759-1d4ec69d-83c7-4153-b54f-36e87347755a.png)

**Comment by KingAlexey212** [comment]
Problem fixed by deleting config file.

**Comment by cheatfreak47** [comment]
Uh, I am also getting this error on a fresh install of the latest version. :V

**Comment by programmer2514** [comment]
I can't debug it atm because I have no electricity after the storm that went through the other day, but if you're getting that same exact error, it's caused by a corrupted settings file.

**Comment by cheatfreak47** [comment]
Oh dang! I had something similar about 2 weeks back, hope you get your power back soon.
Upon further inspection, my error is slightly different from the one above. I'll make a new issue.
