### ISSUE TITLE
CollapsibleUI conflicts with SpotifyControls when using Dark Matter theme. 

### ISSUE THREAD

**Issue by patrickzhou1234** [programmer2514/BetterDiscord-CollapsibleUI#35]
When I collapse server and/or channels, spotifycontrols seems to be bugged. 
![image](https://user-images.githubusercontent.com/83720283/179563540-4263a3f7-2140-40a8-adc5-b8e568b692e3.png)

**Comment by programmer2514** [comment]
I'll look into this :)

**Comment by patrickzhou1234** [comment]
Thanks a ton for your hard work. :)

**Comment by programmer2514** [comment]
I can't seem to reproduce it. What theme are you using?

**Comment by patrickzhou1234** [comment]
I'm not using any theme. I'm just using the [https://betterdiscord.app/plugin/SpotifyControls](url) plugin. When I collapse the channels, it bugs the interface.

**Comment by programmer2514** [comment]
> EDITED: I figured it out I was using the dark matter theme. It was bugged bc of that. I switched to softx and it now works.

Okay, yeah, I've had a few theme conflicts since this does mess with the UI. I'll attempt to write in some compatibility code, it shouldn't be too difficult
