### ISSUE TITLE
cuts window bar buttons by 4px

### ISSUE THREAD

**Issue by AlexPlay1** [programmer2514/BetterDiscord-CollapsibleUI#36]
When this plugin is enabled, buttons on window bar gets cut by 4px from above (non-clickable) ([screenshot 1](https://user-images.githubusercontent.com/42866177/183301245-d31236bf-3abd-45a5-93f3-308758f1e5ee.png)). When I set window bar - height in settings of the plugin to 22px (default discord value) - it expands by 4px down ([screenshot 2](https://user-images.githubusercontent.com/42866177/183301246-5f0b05f0-7bdc-4856-ab09-e2919376df8f.png))
Expected behavior: to look like default discord ([screenshot 3](https://user-images.githubusercontent.com/42866177/183301247-b7fcbb71-1dba-466c-9fcc-e97d0f2d0d24.png))

![screenshot 1](https://user-images.githubusercontent.com/42866177/183301245-d31236bf-3abd-45a5-93f3-308758f1e5ee.png)
![screenshot 2](https://user-images.githubusercontent.com/42866177/183301246-5f0b05f0-7bdc-4856-ab09-e2919376df8f.png)
![screenshot 3](https://user-images.githubusercontent.com/42866177/183301247-b7fcbb71-1dba-466c-9fcc-e97d0f2d0d24.png)

**Comment by programmer2514** [comment]
Thanks for the report :)
