### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by adsdawdfawdcwacdaw** [programmer2514/BetterDiscord-CollapsibleUI#37]
plugin is not compatible with Lighty's message logger v2 plugin, the button covers it up. also appears to not play nice with user notes by creating 2 member list buttons.

**Comment by programmer2514** [comment]
> plugin is not compatible with Lighty's message logger v2 plugin, the button covers it up.
Unfortunately you are going to have to ask Lighty to account for this, as the plugin you mentioned is against BetterDiscord's and Discord's ToS and I cannot support it.

> also appears to not play nice with user notes by creating 2 member list buttons.
I tried it with UserNotes, it works fine? Are you certain that that is the plugin it is conflicting with?
