### ISSUE TITLE
[BUG] Collapsible UI with Channel DM - Members List

### ISSUE THREAD

**Issue by zluckytraveler** [programmer2514/BetterDiscord-CollapsibleUI#39]
For some reason when both plugins Collapsible UI and [Channel DMs](https://github.com/Strencher/BetterDiscordStuff/tree/master/ChannelDms) are enabled the member list ends up having an issue where it will only close half way when on members, and when selecting DMs to collapse it, it will not at all. When switching back to members after selecting DMs it will lock up and no longer collapse half way anymore. 

The only way to get it to work properly is by being selecting DMs and then changing the channel which will move the members list icon from the furthest right position to 3rd from the right, which will allow you to collapse the members list finally.

This adjustment that makes it end up working is only temporary and does not transfer from one guild to the next making these steps have to be repeated. Same goes for anytime you restart or start up the client.

Hopefully this video will help give you a better idea of the issue.

https://user-images.githubusercontent.com/97180817/187059176-ec02a64a-12eb-44ef-8372-cb2cfca3ab4d.mp4

**Comment by programmer2514** [comment]
Yep, this is definitely a plugin incompatibility. It seems like Channel DMs creates its own wrapper container for the members list which is causing my plugin to fail. It should be a relatively easy fix, but it may take me a while to find time around my college classes. Thank you for the report, and sorry for the inconvenience

**Comment by zluckytraveler** [comment]
I completely understand, I hope to see a fix implemented, and cannot wait for it. I absolutely love using this plugin, this is the only issue I've had so far, besides that it's a dream! Best of luck with your classes!
