### ISSUE TITLE
Plugin can not be loaded

### ISSUE THREAD

**Issue by BlueStarBRS** [programmer2514/BetterDiscord-CollapsibleUI#4]
the plugin from plugin repo dont load (outdated 1.10) then i downloaded the github version from here now this:
![image](https://user-images.githubusercontent.com/25110093/127787858-6f27fd3f-548e-4a91-8c4d-95413e57aabe.png)

**Comment by programmer2514** [comment]
This screenshot gives literally no useful information. In what context did this error occur?
The next time this error message appears, please press `Ctrl+Shift+I`, click on the `Console` tab at the top, find the message highlighted in red, and send me a screenshot of that.

**Comment by DS-GitHub** [comment]
![image](https://user-images.githubusercontent.com/37930090/128102469-6b8b6506-224a-44f8-8341-73af96ec9633.png)

**Comment by programmer2514** [comment]
@DS-GitHub This problem is unrelated (see #1). Please download the latest version from Github (`View Raw`, right click, `Save as...`) to fix this issue.

**Comment by DS-GitHub** [comment]
oh thanks! It enabled after I downloaded the latest version of the plugin.
