### ISSUE TITLE
User Settings UI not aligning properly when switching between servers

### ISSUE THREAD

**Issue by dnk-codes** [programmer2514/BetterDiscord-CollapsibleUI#43]
The user settings panel gets aligned to the left instead of the right when switching servers / going to dms
![image](https://user-images.githubusercontent.com/43136638/188451745-69d550b6-a50d-4995-a025-df9e3d029954.png)

I have disabled collapsing of user settings in the plugin config
![image](https://user-images.githubusercontent.com/43136638/188451889-d21869aa-87d6-438e-9e16-6cea90870751.png)

**Comment by dnk-codes** [comment]
I found a solution, not sure if it's possible I just modded the css. 
`class="panels-3wFtMD"` > `container-YkUktl` > + `justify-content: space-between`

**Comment by programmer2514** [comment]
Thanks for the report and the help! Should be fixed in the next release
