### ISSUE TITLE
Crash(?) when enabling/disabling plugins

### ISSUE THREAD

**Issue by alije123** [programmer2514/BetterDiscord-CollapsibleUI#46]
If you enable or disable other betterdiscord plugins, e.g. channel tabs or if you change the username locally via a plugin edit user (probably because it changes the user interface), the plugin will stop working and will be enabled again when you switch to another channel

(no entries in the console)

**Comment by programmer2514** [comment]
This isn't a crash, it's the result of another plugin reloading the UI without triggering a reload event. I'll try to find a fix for it and hopefully get it resolved in the next release.
