### ISSUE TITLE
Feature Request: uncollapse on hover

### ISSUE THREAD

**Issue by proxseas** [programmer2514/BetterDiscord-CollapsibleUI#5]
First of all, I'd like to say that this plugin is amazing and makes Discord a lot cleaner and more pleasant to use. But it would super convenient if it was possible to configure a couple of the collapsible sections of the UI to re-appear when you hover over where they used to be. For example, this extension for Chrome has such functionality: https://github.com/patrickxchong/hide-discord-sidebar.
Also, it would be super neat if it was possible to somehow group the toggler buttons introduced by this extension. Not sure how feasible it is.

**Comment by programmer2514** [comment]
I'll add this to my todo list for v3 :)

**Comment by proxseas** [comment]
That was a quick response... thank you!

**Comment by programmer2514** [comment]
No problem!

**Comment by programmer2514** [comment]
Finished in dev release
