### ISSUE TITLE
When some other BetterDiscord plugin gets update - CollapsibleUI stops working until you toggle it off/on 

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#50]
Steps for reproduction. CollapsibleUI version 5.7.2. BD Core version 1.8.2

1. While everything works fine - wait for some plugin to get updated so BetterDiscord notification pops up
![image](https://user-images.githubusercontent.com/33165440/196707210-61d9c76d-14ae-4920-b849-8863e96c4857.png)

2. Click "All" - plugins above get updates just fine. 

3. CollapsibleUI's buttons are gone 
![image](https://user-images.githubusercontent.com/33165440/196707594-494d7a3e-c771-4d4c-913e-20b87aff26ca.png)

4. But the plugin is still on in settings 
![image](https://user-images.githubusercontent.com/33165440/196707481-91f858a9-63d7-499a-a793-c38406464da4.png)

5. Toggling off/on brings it back to working state

PS. this issue is a summary of the [support thread](https://discord.com/channels/86004744966914048/1030944619711713310/1030944619711713310) in forum channel of BetterDiscord server

**Comment by programmer2514** [comment]
Reopening until this is actually fixed
