### ISSUE TITLE
Not Disabling Ui

### ISSUE THREAD

**Issue by DistrutPioneer** [programmer2514/BetterDiscord-CollapsibleUI#51]
![image](https://user-images.githubusercontent.com/84829838/197514599-7cb59bd6-bec8-49c3-b2f2-391742610321.png)
![image](https://user-images.githubusercontent.com/84829838/197515094-299d43f5-6732-419d-94ae-dabd0b75c281.png)

When Disabled In The Settings The Ui Still Shows Up
(The Call Container Went Away)

**Comment by programmer2514** [comment]
This is not a bug, you're changing the wrong setting. If you would like to entirely disable a button, set its slider to 0 under button customization.
