### ISSUE TITLE
Not working key combination with latest version of the plugin

### ISSUE THREAD

**Issue by CichyCze** [programmer2514/BetterDiscord-CollapsibleUI#52]
Hi! I have a problem with version 6.1.1 of the plugin.

In Czech keyboard layout when you press an equal symbol (first key on the left from backspace) in combination with shift key, it makes a hook symbol (ˇ) which some characters uses (ď, ť, ň). The problem here is that when I do that, it does nothing, but only when I disable the plugin.

It would be lovely to be fixed, because some words mean completely something different without the hook symbol.

Thank you for your attention and sorry for my English if there are any mistakes.

**Comment by Jugom** [comment]
should have read this before making my post in #54 
I have the same issue, but in my case it is the ` instead of the ´
I have a german layout and in case it is related my ` key is just left from the backspace key.

**Comment by CichyCze** [comment]
Oh, interesting. I'm glad to hear that I'm not the only one with this problem 😄

**Comment by programmer2514** [comment]
@CichyCze @Jugom 
If I could work with one of you guys on Discord, that would be great. This is going to be a rather difficult bug for me to solve by myself as I only have a QWERTY keyboard, so if either of you guys would be open for testing out a few alpha builds as I attempt to fix the problem, you can contact me @TenorTheHusky#5076. For the time being though, the issue shouldn't happen if you disable keyboard shortcuts in the plugin settings.

**Comment by Jugom** [comment]
just got the update. dropping by to confirm that it indeed worked. 
and sorry I didn't ready your earlier message but glad you could sort it out.
