### ISSUE TITLE
CollapsibleUI not working after starting up BD and Discord

### ISSUE THREAD

**Issue by Nova1ite** [programmer2514/BetterDiscord-CollapsibleUI#53]
Not working after starting up discord, I have to disable then reenable it to work again
6.1.1 on Canary

![Untitled](https://user-images.githubusercontent.com/115776661/197884916-d3f7be29-2480-4830-b522-5d6a7eaf2e29.png)

**Comment by programmer2514** [comment]
Thanks for the report! I'll have to look into this more once BD is available on Canary again.

**Comment by Nova1ite** [comment]
The error is somewhat different now, but still breaks the plugin...
I'll just show you the error I got, and you could fix it anytime, so no rush.
I'm assuming lots of plugins are breaking since discord updates are very sporadic
![Untitled](https://user-images.githubusercontent.com/115776661/208368847-cb16f7c6-fbdd-42cf-bc1d-614329333811.png)

**Comment by programmer2514** [comment]
Are you still having this issue with the latest version of the plugin? I can't seem to reproduce it on my Canary installation

**Comment by Nova1ite** [comment]
No issues it seems, 6.5.0 probably fixed it...
Thanks for the fix despite BD breaking all the time!
Btw, merry christmas even though it ended already lol
