### ISSUE TITLE
CollapsibleUI makes weird things in fullscreen

### ISSUE THREAD

**Issue by Piripe** [programmer2514/BetterDiscord-CollapsibleUI#55]
When I put Discord in fullscreen with Collapsible UI enabled, I have a weird margin in the left of the screen.
![Wtf collapsible UI in fullscreen](https://user-images.githubusercontent.com/77517308/202563847-26672ac3-3c1f-4f7a-9741-d8455cc2b272.png)

My config file: 
```json
{
  "currentVersionInfo": {
    "version": "6.1.3",
    "hasShownChangelog": true
  },
  "cuiSettingsVersion": "7",
  "disableTransitions": "false",
  "transitionSpeed": "0",
  "disableToolbarCollapse": "false",
  "disableSettingsCollapse": "true",
  "enableFullToolbarCollapse": "false",
  "dynamicUncollapse": "true",
  "dynamicUncollapseDistance": "50",
  "dynamicUncollapseDelay": "0",
  "resizableChannelList": "true",
  "channelListWidth": "237",
  "buttonsOrder": "1,2,4,6,7,3,5",
  "dynamicUncollapseEnabled": "true,true,true,true,true,true,false",
  "disabledButtonsStayCollapsed": "false",
  "settingsButtonsMaxWidth": "100",
  "toolbarIconMaxWidth": "300",
  "membersListMaxWidth": "240",
  "toolbarMaxWidth": "800",
  "userAreaMaxHeight": "300",
  "msgBarMaxHeight": "400",
  "windowBarHeight": "18",
  "collapsedDistance": "0",
  "autoCollapse": "true",
  "autoCollapseThreshold": "0,950,400,200,600,400,550",
  "keyBindsEnabled": "true",
  "keyStringList": "Alt\u002BS,Alt\u002BC,Alt\u002BT,Alt\u002BW,Alt\u002BM,Alt\u002BU,Alt\u002BP",
  "serverListButtonActive": "true",
  "channelListButtonActive": "true",
  "msgBarButtonActive": "true",
  "windowBarButtonActive": "true",
  "membersListButtonActive": "true",
  "userAreaButtonActive": "true",
  "callContainerButtonActive": "true"
}
```

**Comment by programmer2514** [comment]
Huh, that is weird. I can't seem to reproduce this behavior. Have you tried disabling your other plugins to rule out a possible plugin conflict?

**Comment by Piripe** [comment]
It's a conflict with ChannelTabs

**Comment by Piripe** [comment]
I disabled all my themes and plugins and I still have the bug, that's weird.

Here's a record of the bug


https://user-images.githubusercontent.com/77517308/204950911-db5f3dc3-7a6f-4fa5-935c-114d522dd805.mp4

**Comment by Jugom** [comment]
I remember seen that happening before.
But I just re checked now and it was collapsed. but if you hover to the right side, it does show the empty column (as expected?).
Maybe make it so collapsibleUI "disables" itself when going full screen mode?

**Comment by programmer2514** [comment]
Alright, I have figured out how to reproduce this and should have a fix here in the next few days :)
