### ISSUE TITLE
Show/hide 'Member List' sometimes does not properly function in Forum Threads

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#57]
There exist some situations when while observing Forum channels - "Show/Hide Members list" does not work for its threads

Unfortunately, I again do not have proper reproduction steps to see into roots of the problem. But here is one consistent way to trigger such behavior.

1. Open Forum Channel **while** having Members list on 
![image](https://user-images.githubusercontent.com/33165440/205165260-065a6eab-810d-46da-86a6-3dcd8c4e0a81.png)

2. Create a new post > Enter Title, Message > Post it
![image](https://user-images.githubusercontent.com/33165440/205165395-2f034131-b10d-41c6-b855-1c8437ba9804.png)

3. It opens thread view for the just created post. Here press "My Fancy Title" to open it in usual channel view. 
![image](https://user-images.githubusercontent.com/33165440/205165485-242c3686-ccbc-4449-ba39-5d36d640e0dc.png)

4. Now try clicking show/hide 'Member List' and it **will not** hide the members list while it should. 
![image](https://user-images.githubusercontent.com/33165440/205165653-e225ad48-0817-4fd5-99e5-f339aac7d22e.png)

**Comment by Aluerie** [comment]
Looks like using Discord Search breaks the button functionality now. 

Quitting search with "x" breaks Member List until revisit the server. 
![image](https://user-images.githubusercontent.com/33165440/205441541-76446cf9-cb2b-4b04-89c9-57f3bc4119a5.png)

**Comment by programmer2514** [comment]
@Aluerie The latest release should fix it the search issue.
In the future, if a bug is unrelated to the original issue, it is better to just open a new one.
