### ISSUE TITLE
Different Collapse/Uncollapse Distance Thresholds?

### ISSUE THREAD

**Issue by graeioume** [programmer2514/BetterDiscord-CollapsibleUI#58]
(First, this is one of my top 5 MVP plugins - amazing work!)

It would be super useful to me for avoiding frustration if I could customize both the threshold at which each element opens and also the threshold for closing.

I know there was a slider under Advanced that seems to have disappeared for now - maybe each slider could have two knobs? One for each threshold?

**Comment by programmer2514** [comment]
ZeresPluginLibrary v2.0.9 is currently broken. However, BetterDiscord's updater is also broken currently so you will have to download v2.0.10 [manually](https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js) (Right-click > Save As...) and then *don't* update when it prompts you to, as that will just revert back to the broken version. That will fix the missing settings options.

As far as having separate closing/opening thresholds, I can implement that fairly easily. I should be able to get that released in a few hours :)
