### ISSUE TITLE
server list css resets with serverfolder.js

### ISSUE THREAD

**Issue by JohnWeak1** [programmer2514/BetterDiscord-CollapsibleUI#60]
the server list element CSS resets to nothing when pressing an arrow key or clicking on the "wrapper-1_HaEi" container and while using serverfolder.js (resulting in the server list un-collapsing)

it is not possible to re-collapse the server list until you update the page by switching server or channel

before the bug (selecting "wrapper-1_HaEi guilds-2JjMmN hasSideBar-sda9Fa"):
![image](https://user-images.githubusercontent.com/42245432/205593746-9e8e73bb-d555-4476-9bd9-d43e54062269.png)

after the bug :
![image](https://user-images.githubusercontent.com/42245432/205593937-b938ddea-f0c2-42a3-9799-92b5fc28b665.png)

**Comment by programmer2514** [comment]
Fixed in 5d7fca0
