### ISSUE TITLE
Channels column auto expands with every received message. 

### ISSUE THREAD

**Issue by Jugom** [programmer2514/BetterDiscord-CollapsibleUI#61]
Just as the tittle says. every time a new message comes, the channels column auto expands. if I move my mouse over the discord window it will collapse again until the next message arrives.
Happens both with Discord being actively used or if I just have it opened in a secondary monitor.
Every time. gotta mouse over for it to collapse.

**Comment by programmer2514** [comment]
This should mostly be fixed. It's always gonna be a bit weird just due to Discord's way of handling the user receiving messages, but it should at least remain collapsed
