### ISSUE TITLE
Toolbar disappers

### ISSUE THREAD

**Issue by zany130** [programmer2514/BetterDiscord-CollapsibleUI#66]
Ever since version 6.4.1, the top toolbar with the inbox and all of the collapsible uisettings disappears after switching between several channels

Discord version:
Stable 165485 (07d8b41) Host 0.0.22 Linux 64-Bit (6.0.14-272-Tkg-Bmq)

with better discord 1.8.4

![image](https://user-images.githubusercontent.com/25832539/209258000-9db5d913-f083-4449-ba45-95926f47214b.png)

Everything above the red line is just not on the window disabling  collapsible UI and renableing fixes the issue until I browse a few more servers and it breaks again

EDIT: 

seems like it only happens if you auto-hide the message box at the bottom after disabling the auto hide for that I no longer get this issue

**Comment by programmer2514** [comment]
Well, that's definitely odd 🤔
I was able to reproduce it, so hopefully I'll have a fix here soon

**Comment by programmer2514** [comment]
Update: Apparently this is caused by an incompatibility with DevilBro's SplitLargeMessages plugin
