### ISSUE TITLE
Too many lines with an attachment in chat can causes hidden elements to reshow/move about

### ISSUE THREAD

**Issue by andrewcartwright1** [programmer2514/BetterDiscord-CollapsibleUI#67]
To replicate this issue consistently i've been entering up to 10 lines each with some random strings then adding an image attachment and clicking into the messages above.

this then causes the user bar to show along the bottom (even though hidden)

![image](https://user-images.githubusercontent.com/10059155/210016692-84450f4d-f5bd-42a6-bed5-d16f825c9c6e.png)

To resolve this, I expand the channel list, hover over user bar and then move off it to rehide it.
This then has an effect of shifting content about causing some elements to disappear, reappear or be completely cutoff

(boosted server icon can reshow, the buttons channel title bar disappears (in some cases will be appear cut off), the text box can sometimes shift out of view so new lines are not visible

![image](https://user-images.githubusercontent.com/10059155/210017040-6eae2ba5-fd8a-44fc-9f7e-21fccbdf36e5.png)
![image](https://user-images.githubusercontent.com/10059155/210016143-42752b5a-7482-47a9-9ec7-121c24c8e055.png)

My settings are as followed, I use discord on a portrait monitor which is 1200x1920, windows 11

```
{
    "currentVersionInfo": {
        "version": "6.5.1",
        "hasShownChangelog": true
    },
    "cuiSettingsVersion": "8",
    "disableTransitions": "false",
    "transitionSpeed": "250",
    "disableToolbarCollapse": "true",
    "disableSettingsCollapse": "true",
    "enableFullToolbarCollapse": "false",
    "dynamicUncollapse": "true",
    "dynamicUncollapseDelay": "15",
    "autoCollapse": "true",
    "autoCollapseThreshold": "500,1201,400,200,1201,1873,550",
    "resizableChannelList": "false",
    "channelListWidth": "0",
    "buttonsOrder": "1,2,4,6,7,3,5",
    "dynamicUncollapseEnabled": "true,true,false,false,true,true,false",
    "disabledButtonsStayCollapsed": "false",
    "keyBindsEnabled": "false",
    "keyStringList": "Alt+S,Alt+C,Alt+T,Alt+W,Alt+M,Alt+U,Alt+P",
    "settingsButtonsMaxWidth": "100",
    "toolbarIconMaxWidth": "300",
    "membersListMaxWidth": "240",
    "toolbarMaxWidth": "800",
    "userAreaMaxHeight": "300",
    "msgBarMaxHeight": "400",
    "windowBarHeight": "18",
    "collapsedDistance": "0",
    "serverListButtonActive": "true",
    "channelListButtonActive": "false",
    "windowBarButtonActive": "true",
    "userAreaButtonActive": "false",
    "callContainerButtonActive": "true",
    "msgBarButtonActive": "true",
    "membersListButtonActive": "false",
    "dynamicUncollapseDistance": "30,30,30,30,30,30,30",
    "dynamicUncollapseCloseDistance": "30,30,30,30,30,30,30",
    "conditionalAutoCollapse": "false",
    "autoCollapseConditionals": ",,,,,,",
    "profilePanelMaxWidth": "340"
}
```

Thank you very much for developing a fantastic plugin, This makes discord more ui friendly for my monitor :D, especially in voice chats

**Comment by programmer2514** [comment]
Thank you so much for the detailed reports!
Both this issue and #68 should now be fixed in v6.5.2 :)
