### ISSUE TITLE
Think its a bug 

### ISSUE THREAD

**Issue by iGetUploaded** [programmer2514/BetterDiscord-CollapsibleUI#69]
So when I go to my DMs the UserProfile shows on on the right and when I go to get rid of it and then to a server the members no longer show up. I got to click the MemberList button to see them again

**Comment by programmer2514** [comment]
This is actually intended for the time being, although I plan on fixing it in the near future. The user profile is currently treated as if it were the members list.

**Comment by iGetUploaded** [comment]
Ohh okay thanks for the info

**Comment by programmer2514** [comment]
This should be fixed in the latest release
