### ISSUE TITLE
Friendlist opens even if cursor isn't that close

### ISSUE THREAD

**Issue by Zzeyy** [programmer2514/BetterDiscord-CollapsibleUI#70]
https://user-images.githubusercontent.com/97387354/213693700-aa2fb05d-5038-45dc-9a96-e2fc85b9a748.mp4

**Comment by Zzeyy** [comment]
Just to clarify, there's a blur in the video.

**Comment by Zzeyy** [comment]
This issue makes working with servers slightly irritating.

**Comment by programmer2514** [comment]
This is not a bug, it's just the default.
It can easily be changed in the plugin settings under `Dynamic Uncollapse > Channel List Opening/Closing Distance`

**Comment by Zzeyy** [comment]
Even if it is default and can be changed, it's just way too far.
