### ISSUE TITLE
Collapsing area with people in call

### ISSUE THREAD

**Issue by Vxson** [programmer2514/BetterDiscord-CollapsibleUI#73]
The area in a DM or group DM always collapses to the minimum whenever you click out or open settings on discord. The only thing I have on with the plugin is hiding servers and groups with a bind. 

I always pull it down a bit for a bigger image as we usually play with cameras and/or screen share, but it goes back to minimum no matter what I do if I click out.

![屏幕截图_20230202_044231](https://user-images.githubusercontent.com/75351289/216158844-5826c99a-38e9-4dd0-9e4a-8d7e643c9436.png)

**Comment by Vxson** [comment]
![discord pull](https://user-images.githubusercontent.com/75351289/216160219-e001c23c-00d1-4a6f-b49c-87bc3f25110e.gif)

**Comment by programmer2514** [comment]
Alright, this should be fixed in v7.0.4. Apologies for the delay.

**Comment by Vxson** [comment]
Awesome dude! Thank you so much for your work!
