### ISSUE TITLE
the button of the memberlist dont disappear

### ISSUE THREAD

**Issue by speedlorenzo12** [programmer2514/BetterDiscord-CollapsibleUI#74]
the button of the memberlist dont disappear for a unknown reason (i use italian discord)

**Comment by programmer2514** [comment]
I'm going to need a bit more information on what exactly is causing this to happen.
Do you have any other plugins enabled? Does the problem persist if you disable them?
If you open the developer console (Ctrl+Shift+I, console tab), are there any red/yellow highlighted messages that start with `[CollapsibleUI]` in blue?

**Comment by speedlorenzo12** [comment]
no plugin generates problems but I didn't understand the console issue but I notice that when I go to see the discord symbol of the memberlist the command display:none; is underlined to indicate that something deletes that command

**Comment by programmer2514** [comment]
What is CustomizableToolbar? It seems that a theme stylesheet is overriding CollapsibleUI's
