### ISSUE TITLE
Update Notification will not clear

### ISSUE THREAD

**Issue by MaxS890** [programmer2514/BetterDiscord-CollapsibleUI#77]
Top Notification Bar insists there is an update...
![image](https://user-images.githubusercontent.com/36490238/220454522-43d32c2e-8bdf-4065-9574-820bd6aa697d.png)

No update available, restarting and reinstalling doesn't resolve?
![image](https://user-images.githubusercontent.com/36490238/220454611-5ba4ec58-8422-4786-a46a-4217e54b04e7.png)

Thanks!

**Comment by programmer2514** [comment]
This is unfortunately an issue with BetterDiscord itself, not CollapsibleUI. They are implementing a new integrated updater and it's pretty broken currently. Try clicking on the name of the plugin in the notification itself and see if that works. If not, manually downloading the latest release from here should fix it.
