### ISSUE TITLE
Request: Options GUI

### ISSUE THREAD

**Issue by SuitYourself** [programmer2514/BetterDiscord-CollapsibleUI#8]
Not sure if this is the correct place to post, forgive me if it is not.
Great addon.
Would love to see an options menu to disable and hide certain buttons that we don't use due to a theme and/or other addons we may be running.

In my case, I don't need the TitleBar icon option nor the typing area option since the theme/plugins I ran remove the title bar and create a new message window area.

Would also be nice to  have the ability to add or subtract how far something slides (in case we are running a theme which is say 100 pixels wider on one of the option given). 

Would be great if there was also a speed changing option where we could adjust the speed to what we prefer.

These are all cosmetic gui based option setting and none of it is needed right away.  Just ideas for a future update. 

Once again, thanks for your time and your addon.

**Comment by JustWhelmed** [comment]
In my case I'd like to disable the collapsing of the Mute/Defean buttons into the User Settings button because it conflicts with a Game Activity Button Toggle plugin I have. 

Would removing certain lines in the code work? If so, which should I delete?

**Comment by programmer2514** [comment]
@JustWhelmed I'm actually in the process of implementing a settings panel to do what you're saying as we speak. Should be done by tomorrow. For right now though, you should be able to set `disableSettingsButtonsCollapse` to true in the plugin's config file (`%appdata%\BetterDiscord\plugins\CollapsibleUI.plugin.json` or something like that) and then reload Discord
