### ISSUE TITLE
Error 9000 

### ISSUE THREAD

**Issue by ChikaTokisaki** [programmer2514/BetterDiscord-CollapsibleUI#83]
I downloaded UI and get error 9000, so what do I need to do?
![image](https://user-images.githubusercontent.com/128670308/227686992-617bfba7-b910-48ea-bb21-0eff768a4ead.png)

**Comment by programmer2514** [comment]
This is actually an issue with the BetterDiscord core (see the [support thread on Discord](https://discord.com/channels/86004744966914048/1080245227027189840)). Downloading my plugin must have triggered the update that broke BetterDiscord. They are working on a fix, but for the time being, you can get it to work by deleting/moving all of your plugins and restarting Discord.
