### ISSUE TITLE
Button Customization settings page has unusable volume-mixer icons after BetterDiscord 1.9 update 

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#84]
Not sure if I'm at fault but Button Customization settings page is not really usable now. Before it was horizontal scale-line with numbers, now it's messed up volume-mixer icon with irresponsive-bar. 

it works as in random clicks around put floats into `.config.json` but it is definitely not user-friendly because on reload the plugin doesn't understand such positions and considers them disabled.

![image](https://user-images.githubusercontent.com/33165440/228593133-8991d124-3c23-4e8c-a9b3-0552b9422652.png)

**Comment by programmer2514** [comment]
This is due to an outdated version (v2.0.13) of ZeresPluginLibrary. It is fixed in the latest version, which can be downloaded here: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js (right-click > Save As...).
