### ISSUE TITLE
What does autocollapse actually do?

### ISSUE THREAD

**Issue by Aluerie** [programmer2514/BetterDiscord-CollapsibleUI#88]
I don't understand what it does, maybe wording is confusing, maybe it's bugged? 

![image](https://user-images.githubusercontent.com/33165440/234323547-70b0da05-dd2b-4869-b83d-3accf87dac02.png)

"Enables auto-collapse of UI elements based on window size" - okay so the input number from me is a Discord window width/height. 
"Maximum width for element to remain uncollapsed" - okay so something should happen with channel list when I cross between 599-601 width, but what? "Max ... uncollapsed" so it should collapse after reaching 601 since it's max ? But that doesn't make sense. 

I would suppose the feature means (at least I want it to mean) that for example 

the channel list should get 
* collapsed when window is under 600 (so since discord window is *small* - it gives me more space to show conversation)
* uncollapsed when window is above 600 (so since discord window is *big* - it can fit channel list without losing conversation space)

but nothing happens: 

https://user-images.githubusercontent.com/33165440/234324401-d12bcfee-42cd-431b-9b44-f6ea73826fc3.mp4

I tried toggling on off all kinda settings to find contradictions/incompatibilities and as you can see - my other plugins are off, my current settings are https://mystb.in/EyesUntilGardens

Unfortunately, I'm clueless at JS so can't even analyse code to guess what should/is supposed to happen.

**Comment by programmer2514** [comment]
This is intended behavior - apparently I just forgot to document it properly.

You are correct about what Autocollapse does, but it is dependent on Dynamic Uncollapse.
