### ISSUE TITLE
Pressing shift shows the window bar

### ISSUE THREAD

**Issue by Kevin1Smid** [programmer2514/BetterDiscord-CollapsibleUI#89]
I have all keyboard shortcuts disabled but whenever I press shift the window bar opens. This is really weird when typing capital letters as it flashes open and close

**Comment by Kevin1Smid** [comment]
This is only a problem when I have Enable Full Toolbar Auto-collapse enabled

**Comment by programmer2514** [comment]
I cannot seem to reproduce this behavior. Could you send me your config file and a list of plugins that you have enabled?
