### ISSUE TITLE
Collapsible UI auto expands when pressing shift.

### ISSUE THREAD

**Issue by CannibalKon** [programmer2514/BetterDiscord-CollapsibleUI#90]
#71 

I have noticed this was a previous issue months ago, but I have been struggling with this issue for months and didn't realize until looking into these issues that it was caused by the shift key.

I have tested it a few times after learning this and it is indeed tied solely to the pressing of the shift key. Things seem to freeze and all UI elements expand for a moment before the plugin closes them all again.

I have attached all plugins I am using below. If there is anything else needed to help assist with this nefarious issue, I would be happy to help.

![image_2023-06-09_055736373](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/35207251/31e8c7f8-429f-4ab9-a55a-d68a641e5e92)

**Comment by gzmuszynski** [comment]
I also have this issue. No other plugins, just this and of course the zeres plugin library dependancy.
[CollapsibleUI.config.txt](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/files/12218094/CollapsibleUI.config.txt)
