### ISSUE TITLE
When Member List is Collapsed, nothing moves over

### ISSUE THREAD

**Issue by TrippaTepis** [programmer2514/BetterDiscord-CollapsibleUI#93]
When I collapse the member list, the UI doesn't extend to cover that spot (this does not change depending on auto-collapse or manual collapse). It just leaves an empty hole. No other collapsible element does this.

![image](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/132021436/08b212e7-7904-4dd6-9806-7f62950eedd9)

Version Used: 7.3.0
BD Version: 1.9.3
Discord Version: Stable 235819

There was a silent update that broke something.

Edit: It's also worthy to note that resizing the members list causes it to very quickly shrink in on itself with even the smallest tweak to make it smaller and leave an empty hole, making it look as if the members list is collapsed.

**Comment by Doomelf** [comment]
Wasn't having this issue, until KB5031356 got installed.

**Comment by amoses252** [comment]
Yeah, I got this problem recently too

**Comment by ForeverFloating** [comment]
I am having this same issue for version 8.0.0 of the plugin on Discord Stable 261973 (954e1a5), BetterDiscord v1.9.7
