### ISSUE TITLE
Nothing collapsing or expanding at all

### ISSUE THREAD

**Issue by Nova1ite** [programmer2514/BetterDiscord-CollapsibleUI#94]
Version Used: 7.3.0
BD Version: 1.9.3
Discord Version: PTB 237477

I think it broke... nothing is autocollapsing at all even with enabling and disabling the plugin. I have dynamic collapse on.

![Screenshot 2023-10-16 124708](https://github.com/programmer2514/BetterDiscord-CollapsibleUI/assets/115776661/d4bcdfc8-6e46-4792-8aad-939856f8f35f)

**Comment by programmer2514** [comment]
It appears that Discord has broken their style names again in PTB - it's an easy fix but it isn't backwards-compatible, so I likely will not release it until the changes are made on Stable.

**Comment by Doomelf** [comment]
Having the same issue on the stable build (237546). The weird part is nothing else besides #93 was wrong, but after starting PC today suddenly nothing was autocollapsing. The extra buttons to show or hide sections also aren't appearing. Nothing is changing when enabling or disabling the plugin.

**Comment by xunkar** [comment]
Confirming this is happening on Stable 237546 (c8efe13)

Same error message in the console.
