### ISSUE TITLE
Plugin is entirely non-functional

### ISSUE THREAD

**Issue by TrippaTepis** [programmer2514/BetterDiscord-CollapsibleUI#97]
After the update today, nothing in the plugin works. Cannot collapse/uncollapse any element except the Members List (the buttons do not even appear at the top of Discord when hovering over the Member List button), and even the keyboard shortcuts do nothing. Cannot resize the Members List or Channel List. Dynamic collapse/uncollapse is non-functional.

Discord Version: Stable 238110 (fcf9e98)
CollapsibleUI Version: 7.4.0

EDIT: The buttons to collapse reappear *only* if you aren't using a theme. They work *there*, but the dynamic auto-uncollapse does not function.

**Comment by programmer2514** [comment]
Discord has released another update in the 8 hours since I published the fix for my plugin. I am working on resolving it right now.
